"""add incidents table

Revision ID: 9fcaca6b764e
Revises: 
Create Date: 2026-08-25 06:03:21.246057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9fcaca6b764e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('needs_immediate_help', sa.Boolean(), nullable=False),
    sa.Column('category', sa.Enum('ANIMAL_SIGHTING', 'ANIMAL_IN_DISTRESS', 'ANIMAL_BLOCKING_PATH', 'AGGRESSIVE_BEHAVIOR', 'OTHER', name='incidentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'QUEUED_OFFLINE', 'VERIFIED', 'CLOSED', name='incidentstatus', native_enum=False, length=16), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_description', sa.Text(), nullable=True),
    sa.Column('location_accuracy_low', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
